### PR TITLE
Fixdeps 0.7

### PR DESCRIPTION
**Pull request by scheidan**
Removed all dep warnings for 0.7

I've followed this guide until step 5:
https://discourse.julialang.org/t/updating-packages-from-julia-v0-6-to-0-7/5103

Thanks for this great package! I hope that helps.

### CODE REVIEW

**Comment by scheidan** [comment]
It seems that `Base.info` exists in `0.7` but was removed in `1.0` which breaks the package installation.
Nor sure how to find it again... Of course we could simply remove the `info`s.

**Comment by giordano** [comment]
> It seems that `Base.info` exists in `0.7` but was removed in `1.0` which breaks the package installation.
Nor sure how to find it again... 

Now it's a macro: [`@info`](https://docs.julialang.org/en/v1/stdlib/Logging/#Base.CoreLogging.@logmsg).

**Comment by scheidan** [comment]
Is there anything else I should add/change?

**Comment by akels** [comment]
One can also add `Project.toml` and `Manifest.toml` file to make the package compatible with the new Pkg.  

[Cubature.zip](https://github.com/stevengj/Cubature.jl/files/2593145/Cubature.zip)

**Comment by gwater** [comment]
I've been using this branch for a while and it seems pretty stable. Any chance it could be merged into master soon?

**Comment by stevengj** [comment]
Thanks!

**Pull request merged**
