### PR TITLE
Fix for Julia 0.5: symbol → Symbol

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by giordano** [comment]
Also `OS_NAME` is deprecated in Julia 0.5, but its replacement `Sys.KERNEL` isn't available for Julia 0.4.  `@static is_*()` should be used instead?

**Comment by giordano** [comment]
Uh, second commit makes Travis fail with Julia 0.4 on OS X: https://travis-ci.org/stevengj/Cubature.jl/builds/136011028  Instead the first one worked with that configuration: https://travis-ci.org/stevengj/Cubature.jl/builds/136008876  Internet connection or what?  I don't have an OS X box to test with.

**Comment by giordano** [comment]
I guess this can be closed as well after pull request #19.  But the problem with `Sys.KERNEL` is still there, probably (didn't try a recent Julia version though).

**Comment by stevengj** [comment]
Thanks, I updated it to use `is_apple()` and `is_windows()`.

**Pull request closed without merging**
